
- name: nginx installation
  ansible.builtin.shell:
    name: nginx
    state: installed

- name : start and enable nginx
  ansible.builtin.service :
    name : nginx
    state : started
    enabled : yes
- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
- name : Create html directory
  ansible.builtin.file :
    path : /usr/share/nginx/html/
    state : directory
- name: download the frontend artifact
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp
- name : extract the frontend artifact
  ansible.builtin.unarchive :
    src : /tmp/frontend.zip
    dest : /usr/share/nginx/html/
    remote_src : yes
- name : copy roboshop.conf
  ansible.builtin.template :
    src : roboshop.conf
    dest : /etc/nginx/default.d/roboshop.conf


- name : copy nginx conf file
  ansible.builtin.template :
    src : nginx.conf
    dest : /etc/nginx/nginx.conf

- name : restart frontend
  ansible.builtin.service :
    name : nginx
    state : restarted
    enabled: yes

- name: import filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter