
- name: create user roboshop
  ansible.builtin.user :
    name: "{{app_user}}"

- name: clean up old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name : extract the catalogue artifact
  ansible.builtin.unarchive :
    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest : /app
    remote_src : yes