## THIS STRP IS NO MORE NEEDED AS CI PIPELINE IS TAKINGCARE
#- name: Install maven
#  ansible.builtin.yum :
#    name: maven
#    state: installed

- name: Install java
  ansible.builtin.yum :
    name: java-17-openjdk
    state: installed

- name: include task list in a play
  ansible.builtin.import_tasks:
    file: app_prereq.yaml

 #THIS STRP IS NO MORE NEEDED AS CI PIPELINE IS TAKINGCARE
#- name: download maven dependencies
#  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#    chdir: /app


- name: include schema load
  ansible.builtin.import_tasks:
    file: schema_setup.yaml

- name: include systemd service
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml


- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter