- name: setup NPM resource
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: include task list in a play
  ansible.builtin.import_tasks:
    file: app_prereq.yaml

#THIS STRP IS NO MORE NEEDED AS CI PIPELINE IS TAKINGCARE
- name: install dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: include schema load
  ansible.builtin.import_tasks:
    file: schema_setup.yaml

- name: include systemd service
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml


- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter