- name: install python
  ansible.builtin.yum:
    name: "{{item}}"
    state: installed
  loop:
    - python36
    - gcc
    - python3-devel


- name: include task list in a play
  ansible.builtin.import_tasks:
    file: app_prereq.yaml

- name: install dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app


- name: include systemd service
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml