- name: Load schema mongodb
  when: schema_setup == "mongo"
  block:
    - name : copy mongo repo in yum.repos.d
      ansible.builtin.copy :
        src : mongo.repo
        dest : /etc/yum.repos.d/mongo.repo
    - name :  mongodb client software installation
      ansible.builtin.yum :
        name: mongodb-org-shell
        state: installed


    - name: Download DocDB PEM File
      ansible.builtin.get_url:
        url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name: Load Schema
      ansible.builtin.shell: mongo --ssl --host {{ lookup('aws_ssm', '{{ env }}.docdb.db_endpoint', region='us-east-1' ) }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', '{{ env }}.docdb.db_user', region='us-east-1' ) }} --password {{ lookup('aws_ssm', '{{ env }}.docdb.db_pass', region='us-east-1' ) }} </app/schema/{{component}}.js


- name: Load schema mysql
  when: schema_setup == "mysql"
  block:
    - name :  mongodb client software installation
      ansible.builtin.yum :
        name : mysql
        state : installed
    - name: load catalogue data(schema)
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{ env }}.rds.db_host', region='us-east-1' ) }}  -u{{ lookup('aws_ssm',  '{{ env }}.rds.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{ env}}.rds.db_pass', region='us-east-1' ) }} < /app/schema/{{component}}.sql

